### ISSUE TITLE
Potential packaging issue incompatible with PHP 8.1

### ISSUE THREAD

**Issue by CapturedMomentum** [amalfra/supportbee#6]
@amalfra Good morning!

We upgraded our servers to PHP 7.3 to 8.1 yesterday and are running into an odd issue. In the source code under [`HTTP.php`](https://github.com/amalfra/supportbee/blob/main/src/HTTP.php#L39), there is this function defined:

`protected static function tfTostring(&$value, $key)`

That is all fine and good, but when we pull down the latest package with composer (v1.1.0), that function is packaged into `vendor/amalfra/supportbee/src/SupportBee/API.php`, and that line reads: 

`protected static function tfTostring(&$value, &$key)`

The second argument `$key`, being a pass-by-reference parameter in the package checkout out by `composer`, is throwing an exception:

`SupportBee\API::tfTostring(): Argument #2 ($key) must be passed by reference, value given`

I was going to open a PR to address this, but the actual source code does not appear to contain this issue at all. Do you have any insights as to what might be causing this?

Best regards,
@CapturedMomentum

**Comment by CapturedMomentum** [comment]
@amalfra I got to looking into this further, and it looks like the `composer` version is just quite a bit out-of-date as compared to the source. Is it possible to get an updated version of the composer package?

**Comment by amalfra** [comment]
@CapturedMomentum The main branch has only some commits related to testing and linting changes that shouldn't don't have any PHP file changes than the latest released commit. I can publish a new version with the main changes now.

**Comment by amalfra** [comment]
@CapturedMomentum Can you try the latest published version?

**Comment by CapturedMomentum** [comment]
@amalfra I updated and the issue appears to have gone away, thanks!
